version: "3"

volumes:
  php_test:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hlimouni/inception/data

services:
    nginx_ssl:
        container_name: nginx_ssl
        build:
            context: ./requirements/nginx 
            dockerfile: Dockerfile
        volumes:
            - "php_test:/www:rw"
        ports:
            - "443:443"
        restart: "always"

    php_wordpress:
        container_name: php_wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - "php_test:/www:rw"
        ports: 
            - "9000:9000"
        restart: "always"
    mariadb:
        container_name: mariadb
        build: 
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        volumes:
            - "php_test/www:rw"
        ports: 
            - "3306:3306"
        restart: always
    
