version: "3"

services:
    nginx_ssl:
        container_name: nginx_ssl
        build:
            context: ./requirements/nginx 
            dockerfile: Dockerfile
        ports:
            - "443:443"
            - "80:80"
        restart: "always"
    # php_wordpress:
    #     container_name: php_wordpress
    #     build:
    #         context: ./requirements/wordpress
    #         dockerfile: Dockerfile
    #     ports: 
    #         - "9000:9000"
    
