version: "3"

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hlimouni/data/wordpress_db
  wordpress_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hlimouni/data/wordpress_files
# volumes:
#   php_test:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/hlimouni/inception/data

services:
    nginx_ssl:
        container_name: nginx_ssl
        build:
            context: ./requirements/nginx 
            dockerfile: Dockerfile
        volumes:
            - "wordpress_files:/www"
        ports:
            - "443:443"
        restart: "always"

    php_wordpress:
        container_name: php_wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        volumes:
            - "wordpress_files:/www"
        ports: 
            - "9000:9000"
        restart: "always"

    mariadb:
        container_name: mariadb
        env_file:
            - .env
        build: 
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                - MYSQL_USER=$MYSQL_USER
                - MYSQL_PASSWORD=$MYSQL_PASSWORD
                - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
                - MYSQL_DATABASE=$MYSQL_DATABASE
        volumes:
            - "wordpress_db:/var/lib/mysql"
        ports: 
            - "3306:3306"
        restart: always
        
    
