CREATE USER 'user'@'mariadb' IDENTIFIED BY '123';
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress . * TO 'user'@'mariadb' IDENTIFIED BY '123';
DROP USER IF EXISTS '';
DROP DATABASE IF EXISTS test;
FLUSH PRIVILEGES;